### ISSUE TITLE
Vendored puppet 3.7 doesn't work on newer rubies

### ISSUE THREAD

**Issue by DavidS** [nwops/puppet-retrospec#54]
Using the vendored puppet 3.7 I'm getting the following error. Removing the vendor directory and installing puppet 4.3.2 instead let a simple 'retrospec puppet' run successfully.

```
david@zion:~/git/dasz-configuration$ bundle exec retrospec puppet 
/home/david/gems/ruby/2.3.0/gems/puppet-retrospec-0.12.1/vendor/gems/puppet-3.7.3/lib/puppet/defaults.rb:465: warning: key :queue_type is duplicated and overwritten on line 466
/home/david/gems/ruby/2.3.0/gems/puppet-retrospec-0.12.1/vendor/gems/puppet-3.7.3/lib/puppet/vendor/safe_yaml/lib/safe_yaml/syck_node_monkeypatch.rb:42:in `<top (required)>': uninitialized constant Syck (NameError)
	from /home/david/gems/ruby/2.3.0/gems/puppet-retrospec-0.12.1/vendor/gems/puppet-3.7.3/lib/puppet/vendor/safe_yaml/lib/safe_yaml.rb:197:in `require'
	from /home/david/gems/ruby/2.3.0/gems/puppet-retrospec-0.12.1/vendor/gems/puppet-3.7.3/lib/puppet/vendor/safe_yaml/lib/safe_yaml.rb:197:in `<module:YAML>'
	from /home/david/gems/ruby/2.3.0/gems/puppet-retrospec-0.12.1/vendor/gems/puppet-3.7.3/lib/puppet/vendor/safe_yaml/lib/safe_yaml.rb:132:in `<top (required)>'
	from /home/david/gems/ruby/2.3.0/gems/puppet-retrospec-0.12.1/vendor/gems/puppet-3.7.3/lib/puppet/vendor/require_vendored.rb:4:in `require'
	from /home/david/gems/ruby/2.3.0/gems/puppet-retrospec-0.12.1/vendor/gems/puppet-3.7.3/lib/puppet/vendor/require_vendored.rb:4:in `<top (required)>'
	from /home/david/gems/ruby/2.3.0/gems/puppet-retrospec-0.12.1/vendor/gems/puppet-3.7.3/lib/puppet/vendor.rb:40:in `require'
	from /home/david/gems/ruby/2.3.0/gems/puppet-retrospec-0.12.1/vendor/gems/puppet-3.7.3/lib/puppet/vendor.rb:40:in `require_libs'
	from /home/david/gems/ruby/2.3.0/gems/puppet-retrospec-0.12.1/vendor/gems/puppet-3.7.3/lib/puppet/vendor.rb:53:in `load_vendored'
	from /home/david/gems/ruby/2.3.0/gems/puppet-retrospec-0.12.1/vendor/gems/puppet-3.7.3/lib/puppet.rb:172:in `<module:Puppet>'
	from /home/david/gems/ruby/2.3.0/gems/puppet-retrospec-0.12.1/vendor/gems/puppet-3.7.3/lib/puppet.rb:29:in `<top (required)>'
	from /home/david/gems/ruby/2.3.0/gems/puppet-retrospec-0.12.1/vendor/gems/puppet-3.7.3/lib/puppet/interface.rb:1:in `require'
	from /home/david/gems/ruby/2.3.0/gems/puppet-retrospec-0.12.1/vendor/gems/puppet-3.7.3/lib/puppet/interface.rb:1:in `<top (required)>'
	from /home/david/gems/ruby/2.3.0/gems/puppet-retrospec-0.12.1/vendor/gems/puppet-3.7.3/lib/puppet/face.rb:11:in `require'
	from /home/david/gems/ruby/2.3.0/gems/puppet-retrospec-0.12.1/vendor/gems/puppet-3.7.3/lib/puppet/face.rb:11:in `<top (required)>'
	from /home/david/gems/ruby/2.3.0/gems/puppet-retrospec-0.12.1/lib/retrospec/plugins/v1/plugin/puppet_module.rb:2:in `require'
...
```

**Comment by logicminds** [comment]
Puppet does not support ruby 2.3 especially the version I am vendoring.  The next version of retrospec vendors 4.3.2 so at that time ruby 2.2 would be the latest ruby you can use.  Afaik

**Comment by logicminds** [comment]
@DavidS are puppet gems 4.4+ now compiled?  If so I won't be able to vendor the gem anymore and instead just set a gem dependency requirement.  This would remove some of the portability aspect.

**Comment by logicminds** [comment]
@DavidS if you are interested the future branch is 90% complete (just smoothing out some formatting bugs).  Its a 1.0.0 release as I rewrote almost the entire thing to use puppet 4 parser only.

**Comment by DavidS** [comment]
nice! I wil have to look at that, but don't currently know when I can slot that in :-(
