### ISSUE TITLE
Please update your vendor puppet version

### ISSUE THREAD

**Issue by halberom** [nwops/puppet-retrospec#61]
I would like to dockerize retrospec, however I'm hitting the bug https://tickets.puppetlabs.com/browse/PUP-3902

Thanks

**Comment by logicminds** [comment]
You can check out the future branch which uses 4.3.2

**Comment by logicminds** [comment]
I would also love to see this dockerized!

**Comment by halberom** [comment]
I'm pretty weak on ruby at the moment, and am struggling with the bundler/rake stuff - probably something simple.

Using the below Dockerfile, it builds and installs the gem.
```
FROM alpine:latest

# don't include ri/rdoc with gem installs
RUN echo 'gem: --no-rdoc --no-ri' > /etc/gemrc

# install deps, use ruby-rake package rather than gem, as we want 10.4.2 (per the lock file)
# and the gem version is much newer
RUN apk add --update --no-cache ruby ruby-rake git

# create a user env
ENV HOME /opt/retrospec
ENV GITDIR $HOME/puppet-retrospec
WORKDIR $HOME

# clone the repo with the future branch, required because the vender version of puppet in
# stable has bug https://tickets.puppetlabs.com/browse/PUP-3902
RUN git clone --depth 1 https://github.com/nwops/puppet-retrospec.git --branch future $GITDIR

# do the magic
RUN apk add --update --no-cache --virtual build-deps ruby-dev build-base libxml2-dev libxslt-dev && \
    gem install facter bundler io-console && \
    cd $GITDIR && bundle config build.nokogiri --use-system-libraries && bundle install && bundle exec rake install && \
    apk del build-deps

#RUN rm -rf $GITDIR

VOLUME [$HOME]

ENTRYPOINT ["retrospec"]
CMD ["puppet"]
```

However I get a stacktrace when I test it
```
$ docker run --rm -it --entrypoint /bin/sh -v $(pwd):/opt/retrospec retrospec
/opt/retrospec # retrospec
usr/lib/ruby/gems/2.2.0/gems/puppet-retrospec-1.0.0/lib/retrospec/plugins/v1/plugin/generators/node_generator.rb:8:in `<module:Generators>': uninitialized constant Retrospec::Puppet::Generators::ResourceBaseGenerator (NameError)
	from /usr/lib/ruby/gems/2.2.0/gems/puppet-retrospec-1.0.0/lib/retrospec/plugins/v1/plugin/generators/node_generator.rb:7:in `<module:Puppet>'
	from /usr/lib/ruby/gems/2.2.0/gems/puppet-retrospec-1.0.0/lib/retrospec/plugins/v1/plugin/generators/node_generator.rb:6:in `<module:Retrospec>'
	from /usr/lib/ruby/gems/2.2.0/gems/puppet-retrospec-1.0.0/lib/retrospec/plugins/v1/plugin/generators/node_generator.rb:5:in `<top (required)>'
	from /usr/lib/ruby/gems/2.2.0/gems/puppet-retrospec-1.0.0/lib/retrospec/plugins/v1/plugin/generators.rb:4:in `require_relative'
	from /usr/lib/ruby/gems/2.2.0/gems/puppet-retrospec-1.0.0/lib/retrospec/plugins/v1/plugin/generators.rb:4:in `block in <top (required)>'
	from /usr/lib/ruby/gems/2.2.0/gems/puppet-retrospec-1.0.0/lib/retrospec/plugins/v1/plugin/generators.rb:3:in `each'
	from /usr/lib/ruby/gems/2.2.0/gems/puppet-retrospec-1.0.0/lib/retrospec/plugins/v1/plugin/generators.rb:3:in `<top (required)>'
	from /usr/lib/ruby/gems/2.2.0/gems/puppet-retrospec-1.0.0/lib/retrospec/plugins/v1/plugin/puppet.rb:4:in `require_relative'
	from /usr/lib/ruby/gems/2.2.0/gems/puppet-retrospec-1.0.0/lib/retrospec/plugins/v1/plugin/puppet.rb:4:in `<top (required)>'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /usr/lib/ruby/gems/2.2.0/gems/puppet-retrospec-1.0.0/lib/retrospec-puppet.rb:3:in `<top (required)>'
	from /usr/lib/ruby/gems/2.2.0/gems/retrospec-0.4.0/lib/retrospec/plugin_loader.rb:11:in `load'
	from /usr/lib/ruby/gems/2.2.0/gems/retrospec-0.4.0/lib/retrospec/plugin_loader.rb:11:in `block (2 levels) in load_from_gems'
	from /usr/lib/ruby/gems/2.2.0/gems/retrospec-0.4.0/lib/retrospec/plugin_loader.rb:10:in `each'
	from /usr/lib/ruby/gems/2.2.0/gems/retrospec-0.4.0/lib/retrospec/plugin_loader.rb:10:in `block in load_from_gems'
	from /usr/lib/ruby/gems/2.2.0/gems/retrospec-0.4.0/lib/retrospec/plugin_loader.rb:9:in `each'
	from /usr/lib/ruby/gems/2.2.0/gems/retrospec-0.4.0/lib/retrospec/plugin_loader.rb:9:in `load_from_gems'
	from /usr/lib/ruby/gems/2.2.0/gems/retrospec-0.4.0/lib/retrospec/plugins.rb:10:in `load_plugins'
	from /usr/lib/ruby/gems/2.2.0/gems/retrospec-0.4.0/lib/retrospec/plugins.rb:21:in `plugin_classes'
	from /usr/lib/ruby/gems/2.2.0/gems/retrospec-0.4.0/lib/retrospec/plugins.rb:28:in `plugin_map'
	from /usr/lib/ruby/gems/2.2.0/gems/retrospec-0.4.0/lib/retrospec/cli.rb:13:in `run'
	from /usr/lib/ruby/gems/2.2.0/gems/retrospec-0.4.0/bin/retrospec:5:in `<top (required)>'
	from /usr/bin/retrospec:23:in `load'
	from /usr/bin/retrospec:23:in `<main>'
```

**Comment by logicminds** [comment]
I think what you want:

```
From ruby:2.1
.
.
.

# clone the repo with the future branch, required because the vender version of puppet in
# stable has bug https://tickets.puppetlabs.com/browse/PUP-3902
RUN git clone --depth 1 https://github.com/nwops/puppet-retrospec.git --branch future $GITDIR
RUN gem build  $GITDIR/puppet-retrospec*.gemspec
RUN gem install pkg/puppet-retrospec*.gem

```

If you use the ruby image you don't have to install many of the dev libraries in order to have ruby present.

**Comment by logicminds** [comment]
Also please note the future branch now contains puppet 4.5.2
