### ISSUE TITLE
puppet complains that facter gem does not exist

### ISSUE THREAD

**Issue by logicminds** [nwops/puppet-retrospec#64]
```
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- facter (LoadError)
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/share/gems/gems/puppet-retrospec-1.1.0/vendor/gems/puppet-4.5.2/lib/puppet.rb:10:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/share/gems/gems/puppet-retrospec-1.1.0/lib/retrospec/plugins/v1/plugin/generators/serializers/rspec_dumper.rb:1:in `<top (required)>'
	from /usr/local/share/gems/gems/puppet-retrospec-1.1.0/lib/retrospec/plugins/v1/plugin/generators/resource_base_generator.rb:2:in `require_relative'
	from /usr/local/share/gems/gems/puppet-retrospec-1.1.0/lib/retrospec/plugins/v1/plugin/generators/resource_base_generator.rb:2:in `<top (required)>'
	from /usr/local/share/gems/gems/puppet-retrospec-1.1.0/lib/retrospec/plugins/v1/plugin/generators/acceptance_generator.rb:1:in `require_relative'
	from /usr/local/share/gems/gems/puppet-retrospec-1.1.0/lib/retrospec/plugins/v1/plugin/generators/acceptance_generator.rb:1:in `<top (required)>'
	from /usr/local/share/gems/gems/puppet-retrospec-1.1.0/lib/retrospec/plugins/v1/plugin/generators.rb:4:in `require_relative'
	from /usr/local/share/gems/gems/puppet-retrospec-1.1.0/lib/retrospec/plugins/v1/plugin/generators.rb:4:in `block in <top (required)>'
	from /usr/local/share/gems/gems/puppet-retrospec-1.1.0/lib/retrospec/plugins/v1/plugin/generators.rb:3:in `each'
	from /usr/local/share/gems/gems/puppet-retrospec-1.1.0/lib/retrospec/plugins/v1/plugin/generators.rb:3:in `<top (required)>'
	from /usr/local/share/gems/gems/puppet-retrospec-1.1.0/lib/retrospec/plugins/v1/plugin/puppet.rb:4:in `require_relative'
	from /usr/local/share/gems/gems/puppet-retrospec-1.1.0/lib/retrospec/plugins/v1/plugin/puppet.rb:4:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /usr/local/share/gems/gems/puppet-retrospec-1.1.0/lib/retrospec-puppet.rb:3:in `<top (required)>'
	from /usr/local/share/gems/gems/retrospec-0.4.0/lib/retrospec/plugin_loader.rb:11:in `load'
	from /usr/local/share/gems/gems/retrospec-0.4.0/lib/retrospec/plugin_loader.rb:11:in `block (2 levels) in load_from_gems'
	from /usr/local/share/gems/gems/retrospec-0.4.0/lib/retrospec/plugin_loader.rb:10:in `each'
	from /usr/local/share/gems/gems/retrospec-0.4.0/lib/retrospec/plugin_loader.rb:10:in `block in load_from_gems'
	from /usr/local/share/gems/gems/retrospec-0.4.0/lib/retrospec/plugin_loader.rb:9:in `each'
	from /usr/local/share/gems/gems/retrospec-0.4.0/lib/retrospec/plugin_loader.rb:9:in `load_from_gems'
	from /usr/local/share/gems/gems/retrospec-0.4.0/lib/retrospec/plugins.rb:10:in `load_plugins'
	from /usr/local/share/gems/gems/retrospec-0.4.0/lib/retrospec/plugins.rb:21:in `plugin_classes'
	from /usr/local/share/gems/gems/retrospec-0.4.0/lib/retrospec/plugins.rb:28:in `plugin_map'
	from /usr/local/share/gems/gems/retrospec-0.4.0/lib/retrospec/cli.rb:13:in `run'
	from /usr/local/share/gems/gems/retrospec-0.4.0/bin/retrospec:5:in `<top (required)>'
	from /usr/local/bin/retrospec:23:in `load'
	from /usr/local/bin/retrospec:23:in `<main>'
```

**Comment by logicminds** [comment]
It is assumed that you are working in an environment where the puppet gem already exists and as a result so do it's dependencies like facter and others.  Retrospec was designed to be installed alongside your existing puppet gem and utilize those other gems.
