### ISSUE TITLE
symlink function is unimplemented on this machine

### ISSUE THREAD

**Issue by logicminds** [nwops/puppet-retrospec#66]
When running retrospec on windows the symlink function is not available and retrospec does not run.  This seems to affect windows 7,8.  

Windows 10 may not be an issue.

**Comment by logicminds** [comment]
```
C:/ruby/lib/ruby/2.0.0/fileutils.rb:349:in `symlink': symlink() function is unimplemented on this machine (NotImplementedError)
from C:/ruby/lib/ruby/2.0.0/fileutils.rb:349:in `block in ln_s'
from C:/ruby/lib/ruby/2.0.0/fileutils.rb:1567:in `fu_each_src_dest0'
from C:/ruby/lib/ruby/2.0.0/fileutils.rb:347:in `ln_s'
from C:/test/test.rb:7:in `<class:Test>'
from C:/test/test.rb:1:in `<main>'
```

**Comment by logicminds** [comment]
Possible workaround is to just not use symlinks
